import { sql } from 'drizzle-orm';
import { timestamp, uuid } from 'drizzle-orm/pg-core';

/**
 * Conventions shared by every table.
 *
 * - `id`        — uuid primary key, generated by the DB.
 * - timestamps  — created/updated, UTC, DB-defaulted.
 * - `orgId`     — every tenant-owned table carries this. The Row-Level Security
 *                 policies (see migrations/0001_rls.sql) key isolation on it.
 */
export const id = () => uuid('id').primaryKey().defaultRandom();

export const timestamps = {
  createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
  updatedAt: timestamp('updated_at', { withTimezone: true })
    .notNull()
    .defaultNow()
    .$onUpdate(() => new Date()),
};

/** Marker so a human reading a table knows it is tenant-scoped + RLS-protected. */
export const TENANT_SCOPED = sql``;
